### PR TITLE
Delete Swift13jpg.jpeg

### PR DESCRIPTION
**Pull request by AmaraSinger**

### CODE REVIEW

**Comment by elindow** [comment]
We need to know more about this mysterious picture. Does it have special powers?

**Comment by AmaraSinger** [comment]
no.

**Comment by elindow** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley

**Review by Tavnik-7-8-22 — DISMISSED** [review]
Should be merged to development not production

**Review by elindow — APPROVED** [review]

**Pull request merged**
